service: saree-ecommerce-backend

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    NODE_ENV: ${env:NODE_ENV, 'production'}
    RESERVATION_CLEANUP_INTERVAL_MS: ${env:RESERVATION_CLEANUP_INTERVAL_MS}
    CORS_ORIGINS: ${env:CORS_ORIGINS}
    CLOUDINARY_CLOUD_NAME: ${env:CLOUDINARY_CLOUD_NAME}
    CLOUDINARY_API_KEY: ${env:CLOUDINARY_API_KEY}
    CLOUDINARY_API_SECRET: ${env:CLOUDINARY_API_SECRET}
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
    ADMIN_EMAILS: ${env:ADMIN_EMAILS}
    RESEND_API_KEY: ${env:RESEND_API_KEY}
    RAZORPAY_KEY_ID: ${env:RAZORPAY_KEY_ID}
    RAZORPAY_KEY_SECRET: ${env:RAZORPAY_KEY_SECRET}
    RAZORPAY_WEBHOOK_SECRET: ${env:RAZORPAY_WEBHOOK_SECRET}
    EMAIL_FROM_NAME: ${env:EMAIL_FROM_NAME}
    EMAIL_FROM_ADDRESS: ${env:EMAIL_FROM_ADDRESS}
    FREE_SHIPPING_THRESHOLD: ${env:FREE_SHIPPING_THRESHOLD}

functions:
  api:
    handler: app.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
      - httpApi:
          path: /
          method: ANY
