service: saree-ecommerce-backend

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    NODE_ENV: ${env:NODE_ENV, 'production'}
    CLOUDINARY_CLOUD_NAME: ${env:CLOUDINARY_CLOUD_NAME}
    CLOUDINARY_API_KEY: ${env:CLOUDINARY_API_KEY}
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
    ADMIN_EMAILS: ${env:ADMIN_EMAILS}
    CLOUDINARY_CLOUD_NAME: ${env:CLOUDINARY_CLOUD_NAME}

functions:
  api:
    handler: app.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
      - httpApi:
          path: /
          method: ANY
